language: node_js
node_js:
- 'node'
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
- npm install codecov
script:
- npm run test:unit 
after_success:
- codecov


